### ISSUE TITLE
Compiling on CentOS 6 gives undefined reference to `gnutls_srp_server_get_username'

### ISSUE THREAD

**Issue by rodolfojcj** [nils-ohlmeier/sipsak#55]
Hello.

I'm trying again to manually compile and install sipsak version 0.9.7pre on CentOS 6, however I'm receiving the following error:

    /usr/src/sipsak-0.9.7pre/src/transport.c:458: undefined reference to `gnutls_srp_server_get_username'
    collect2: ld returned 1 exit status
    make[1]: *** [sipsak] Error 1
    make[1]: Leaving directory `/usr/src/sipsak-0.9.7pre'
    make: *** [all] Error 2
    make: Leaving directory `/usr/src/sipsak-0.9.7pre'
    'make -C sipsak-0.9.7pre' failed with 512.

Given that the file /usr/include/gnutls/gnutls.h provided by the `gnutls-devel` package mentions the `gnutls_srp_server_get_username` function, it seems to me like a linking problem, however I don't know how to solve it.

The installed version of `gnutls-devel` is 2.12.23-22.

I'm attaching these files:

- [The full output of the failed compilation and installation](https://github.com/nils-ohlmeier/sipsak/files/2753926/error_centos_6.10_sipsak_0.9.7pre.txt)
- [The full list of CentOS 6.10 installed packages on the system](https://github.com/nils-ohlmeier/sipsak/files/2753921/centos_6.10_installed_rpm_packages.txt)

How could this be solved?

Thanks in advance for your time and attention.

**Comment by nils-ohlmeier** [comment]
Hello,

Thanks for the report. Always interesting to learn in what kind of special configurations all these Unix system out there are configured. Turns out the CentOS for some unknown reason doesn't compile SRP support into it's GNUTLS libs, but still leaves the functions in the header files. Fun times...

I have patch ready in PR #57. Going to merge it momentarily. Would be great if you could update after the merge and report back if it fixes your problem.

**Comment by rodolfojcj** [comment]
Hi Nils.

You're welcome and thanks a lot for your prompt answer.

I tested again after the merge of PR #57, finding that it works :smile: 

Thanks again! :100:
