### ISSUE TITLE
AM_PROG_CC_C_O warning

### ISSUE THREAD

**Issue by Olpag** [nils-ohlmeier/sipsak#82]
Hi Nils,

I run autoreconf --install and get a warning:
Makefile.am:7: warning: compiling 'src/transport.c' in subdir requires 'AM_PROG_CC_C_O' in 'configure.ac'

Running tests end with errors

My configuration:
Centos 7   3.10.0-1160.62.1.el7.x86_64
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.13.4

**Comment by nils-ohlmeier** [comment]
Hello,
Thanks for letting me know. It looks to me like this is caused by the old automake version (thanks for including that in your report) available on Centos 7. But it also looks like it shouldn't be too hard to get a workaround like here https://github.com/scanmem/scanmem/issues/289
I'll have a look some time later.

**Comment by Olpag** [comment]
Thanks for the answer.
I have seen this solution https://github.com/scanmem/scanmem/issues/289, but I don't know C/C++. So I'm having a hard time deciding where to put this macro in the configure.ac file. I'll be grateful if you give me a hint.

**Comment by nils-ohlmeier** [comment]
@Olpag hopefully the last commit above should fix the issue.

**Comment by Olpag** [comment]
Thanks for reply

Last commit fixed the 'AM_PROG_CC_C_O' warning issue

But there was a problem with the tests

[№87](https://github.com/nils-ohlmeier/sipsak/issues/87)
